modLoader="javafml"
loaderVersion="[47,)"
license="BSD-3-Clause"
[[mods]]
modId="holdattack"
version="1.0.0"
displayName="长按冷却攻击"
authors="666nima"
description='''长按攻击键，准星指向实体且武器冷却完全恢复时攻击。原版方块挖掘不变。'''
displayTest="IGNORE_SERVER_VERSION"
[[dependencies.holdattack]]
modId="forge"
mandatory=true
versionRange="[47.4.6,48)"
ordering="NONE"
side="CLIENT"
[[dependencies.holdattack]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"
